create table if not exists public.mlb_teams (
  team_id bigint primary key,
  name text not null,
  abbreviation text,
  team_name text,
  location_name text,
  league_id bigint,
  division_id bigint,
  source_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.mlb_players (
  player_id bigint primary key,
  full_name text not null,
  first_name text,
  last_name text,
  primary_position text,
  bat_side text,
  throw_hand text,
  source_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.mlb_games (
  game_pk bigint primary key,
  season integer not null,
  game_type text not null,
  game_date timestamptz,
  official_date date,
  status_abstract text,
  status_code text,
  status_detailed text,
  venue_id bigint,
  venue_name text,
  away_team_id bigint references public.mlb_teams(team_id),
  home_team_id bigint references public.mlb_teams(team_id),
  away_score integer,
  home_score integer,
  is_final boolean not null default false,
  linescore jsonb not null default '{}'::jsonb,
  game_number integer,
  doubleheader text,
  series_description text,
  series_game_number integer,
  games_in_series integer,
  source_json jsonb not null default '{}'::jsonb,
  source_fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mlb_game_team_stats (
  game_pk bigint not null references public.mlb_games(game_pk) on delete cascade,
  team_id bigint not null references public.mlb_teams(team_id),
  side text not null check (side in ('home', 'away')),
  batting_stats jsonb not null default '{}'::jsonb,
  pitching_stats jsonb not null default '{}'::jsonb,
  fielding_stats jsonb not null default '{}'::jsonb,
  source_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (game_pk, team_id)
);

create table if not exists public.mlb_game_player_stats (
  game_pk bigint not null references public.mlb_games(game_pk) on delete cascade,
  player_id bigint not null references public.mlb_players(player_id),
  team_id bigint not null references public.mlb_teams(team_id),
  side text not null check (side in ('home', 'away')),
  jersey_number text,
  position_abbreviation text,
  batting_order text,
  batting_stats jsonb not null default '{}'::jsonb,
  pitching_stats jsonb not null default '{}'::jsonb,
  fielding_stats jsonb not null default '{}'::jsonb,
  source_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (game_pk, player_id, team_id)
);

create table if not exists public.mlb_source_payloads (
  game_pk bigint not null references public.mlb_games(game_pk) on delete cascade,
  payload_type text not null check (payload_type in ('schedule', 'boxscore')),
  payload jsonb not null,
  fetched_at timestamptz not null default now(),
  primary key (game_pk, payload_type)
);

create table if not exists public.mlb_ingest_runs (
  run_id bigint generated by default as identity primary key,
  season integer not null,
  mode text not null check (mode in ('backfill', 'sync')),
  status text not null check (status in ('running', 'completed', 'failed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  games_found integer not null default 0,
  games_processed integer not null default 0,
  games_skipped integer not null default 0,
  error_details jsonb not null default '[]'::jsonb
);

create index if not exists mlb_games_season_date_idx
  on public.mlb_games (season, official_date);

create index if not exists mlb_games_type_final_idx
  on public.mlb_games (season, game_type, is_final);

create index if not exists mlb_game_player_stats_player_idx
  on public.mlb_game_player_stats (player_id, game_pk);

create index if not exists mlb_game_player_stats_team_idx
  on public.mlb_game_player_stats (team_id, game_pk);

create index if not exists mlb_game_team_stats_team_idx
  on public.mlb_game_team_stats (team_id, game_pk);

alter table public.mlb_teams enable row level security;
alter table public.mlb_players enable row level security;
alter table public.mlb_games enable row level security;
alter table public.mlb_game_team_stats enable row level security;
alter table public.mlb_game_player_stats enable row level security;
alter table public.mlb_source_payloads enable row level security;
alter table public.mlb_ingest_runs enable row level security;

drop policy if exists "MLB teams are publicly readable" on public.mlb_teams;
create policy "MLB teams are publicly readable"
  on public.mlb_teams for select to anon, authenticated using (true);

drop policy if exists "MLB players are publicly readable" on public.mlb_players;
create policy "MLB players are publicly readable"
  on public.mlb_players for select to anon, authenticated using (true);

drop policy if exists "MLB games are publicly readable" on public.mlb_games;
create policy "MLB games are publicly readable"
  on public.mlb_games for select to anon, authenticated using (true);

drop policy if exists "MLB team stats are publicly readable" on public.mlb_game_team_stats;
create policy "MLB team stats are publicly readable"
  on public.mlb_game_team_stats for select to anon, authenticated using (true);

drop policy if exists "MLB player stats are publicly readable" on public.mlb_game_player_stats;
create policy "MLB player stats are publicly readable"
  on public.mlb_game_player_stats for select to anon, authenticated using (true);

drop policy if exists "MLB source payloads are readable by users" on public.mlb_source_payloads;
create policy "MLB source payloads are readable by users"
  on public.mlb_source_payloads for select to authenticated using (true);

drop policy if exists "MLB ingest runs are readable by users" on public.mlb_ingest_runs;
create policy "MLB ingest runs are readable by users"
  on public.mlb_ingest_runs for select to authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on
  public.mlb_teams,
  public.mlb_players,
  public.mlb_games,
  public.mlb_game_team_stats,
  public.mlb_game_player_stats
to anon, authenticated;

grant select on
  public.mlb_source_payloads,
  public.mlb_ingest_runs
to authenticated;
